# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e31c69c9f403aef74bcab9098865bc7893fe2f0896b4f8a322240cf19864a915be5141c4ed3b24d99569f4ee44cc777ec91ad34321bbcbeaf31b560bddf6ea94

test:
  secret_key_base: a07b5e9a6d9c505d26f334ea7612624f7a5bb34df38428baa5fe0b8454895565b3ff91aa0ef2d35b8e96e0428312b21b1c78a2e6270e9fc8b1dacf963904b407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
